version: "3.8"

services:
  ocr_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr_grok_vision_service
    ports:
      - "6262:6262"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6262/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge