version: '3.8'

services:
  gigachat_service:
    build:
      context: .
      dockerfile: Dockerfile
      # Optionally pass build arguments like port if needed, though env file is preferred for runtime config
      # args:
      #   - APP_PORT=${APP_PORT:-8005} # Default if not set in .env during build
    container_name: gigachat_service
    env_file:
      - .env # Load environment variables from .env file in the same directory
    ports:
      # Map the host port to the container port defined in the .env file
      # The format is "HOST_PORT:CONTAINER_PORT"
      # Example: If APP_PORT=8005 in .env, this maps host port 8005 to container port 8005
      - "${APP_PORT:-8005}:${APP_PORT:-8005}" # Use default if APP_PORT is not set
    volumes:
      # Mount the current directory into the container for development (optional)
      # This allows code changes to be reflected without rebuilding the image (if using reload)
      # Comment out for production deployments
      - .:/app
    restart: unless-stopped
    networks:
      - default_network # Connect to a common network if interacting with other services

networks:
  default_network:
    # Define the network or use an external one if defined elsewhere
    # driver: bridge # Default driver
    name: hyper_ocr_network # Example network name, adjust as needed