#version: '3.8'
#
#services:
#  auth:
#    build: .
#    ports:
#      - "8800:8800"
#    env_file:
#      - .env
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    networks:
#      - rumai_network
#
#  db:
#    image: postgres:13
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    networks:
#      - rumai_network
#    healthcheck:   # Thêm healthcheck
#      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#  redis:
#    image: redis:6
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - rumai_network
#    healthcheck:   # Thêm healthcheck cho Redis
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#
#networks:
#  rumai_network:
#    driver: bridge
#
#volumes:
#  postgres_data:
#  redis_data: