version: '3.8'

services:
  receipt-ocr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr_pytesseract_service
    ports:
      - "6464:6464"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6464/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge